"""Templates for the projects BuffStack generates.

These are real, runnable files rather than stubs: a Flask app with a working
in-memory JSON API and an HTML dashboard that fetches from it. The agent
scaffolds from these, then edits them with the other tools.

Placeholders use ``{{TOKEN}}`` and are applied with :func:`render`. That avoids
``string.Template`` and ``str.format``, whose metacharacters (``$``, ``{}``)
collide with the JavaScript and CSS in these files.
"""

from __future__ import annotations

import json
from typing import Any


def render(template: str, **values: Any) -> str:
    """Replace every ``{{KEY}}`` occurrence with ``values[KEY]``."""
    out = template
    for key, value in values.items():
        out = out.replace("{{" + key + "}}", str(value))
    return out


REQUIREMENTS_TXT = """flask>=3.0
pytest>=8.0
"""

RUN_SH = """#!/usr/bin/env bash
# Start the {{PROJECT_NAME}} dashboard. Generated by BuffStack.
set -euo pipefail

PORT="${1:-${PORT:-{{PORT}}}}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$HERE"

if [ ! -d .venv ]; then
  echo "Creating virtualenv..."
  python3 -m venv .venv
fi

./.venv/bin/pip install --quiet --upgrade pip
./.venv/bin/pip install --quiet -r requirements.txt

echo "Serving {{PROJECT_NAME}} on http://0.0.0.0:${PORT}"
export PORT
exec ./.venv/bin/python app.py
"""


APP_PY = '''"""{{PROJECT_NAME}} — a Flask JSON API with an HTML dashboard.

Generated by BuffStack. The in-memory store keeps the project dependency-free;
swap it for a database when persistence matters.
"""

from __future__ import annotations

import os

from flask import Flask, jsonify, render_template, request

# In-memory store keyed by id.
STORE: dict[int, dict] = {}
NEXT_ID = {"value": 1}

# Fields the create endpoint requires. Generated from the entity spec.
REQUIRED_FIELDS = {{REQUIRED_FIELDS_JSON}}


def _next_id() -> int:
    current = NEXT_ID["value"]
    NEXT_ID["value"] += 1
    return current


def _validate(payload: dict) -> list[str]:
    """Return the required fields that are missing or blank."""
    return [
        name
        for name in REQUIRED_FIELDS
        if payload.get(name) is None or payload.get(name) == ""
    ]


def create_app() -> Flask:
    app = Flask(__name__)

    @app.get("/health")
    def health():
        return jsonify({"status": "ok"})

    @app.get("/")
    def dashboard():
        return render_template("dashboard.html")

    @app.get("/api/{{ENTITY_PLURAL}}")
    def list_{{ENTITY_PLURAL}}():
        return jsonify({"items": list(STORE.values()), "count": len(STORE)})

    @app.post("/api/{{ENTITY_PLURAL}}")
    def create_{{ENTITY_SINGULAR}}():
        payload = request.get_json(silent=True) or {}
        missing = _validate(payload)
        if missing:
            return jsonify({"error": "missing required fields", "fields": missing}), 400
        # Spread the payload first so a client-supplied id cannot win.
        record = {**payload, "id": _next_id()}
        STORE[record["id"]] = record
        return jsonify(record), 201

    @app.get("/api/{{ENTITY_PLURAL}}/<int:record_id>")
    def get_{{ENTITY_SINGULAR}}(record_id: int):
        record = STORE.get(record_id)
        if record is None:
            return jsonify({"error": "not found", "id": record_id}), 404
        return jsonify(record)

    @app.delete("/api/{{ENTITY_PLURAL}}/<int:record_id>")
    def delete_{{ENTITY_SINGULAR}}(record_id: int):
        removed = STORE.pop(record_id, None)
        if removed is None:
            return jsonify({"error": "not found", "id": record_id}), 404
        return jsonify({"deleted": record_id})

    # BUFFSTACK:ROUTES

    return app


app = create_app()


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=int(os.getenv("PORT", "{{PORT}}")), debug=False)
'''


DASHBOARD_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{{TITLE}}</title>
  <link rel="stylesheet" href="{{STATIC_PREFIX}}/static/dashboard.css" />
</head>
<body>
  <div class="shell">
    <header class="topbar">
      <div>
        <h1>{{TITLE}}</h1>
        <p class="subtitle">{{SUBTITLE}}</p>
      </div>
      <div class="topbar-actions">
        <span id="status-pill" class="pill pill-unknown">connecting…</span>
        <button id="refresh" class="btn" type="button">Refresh</button>
      </div>
    </header>

    <div id="error" class="error" hidden></div>

    <section class="cards">
      <article class="card">
        <span class="card-label">Records</span>
        <strong id="kpi-count" class="card-value">–</strong>
      </article>
      <article class="card">
        <span class="card-label">API</span>
        <strong class="card-value card-value-sm">{{API_ENDPOINT}}</strong>
      </article>
      <article class="card">
        <span class="card-label">Last refresh</span>
        <strong id="kpi-updated" class="card-value card-value-sm">–</strong>
      </article>
    </section>

    <section class="panel">
      <div class="panel-head">
        <h2>Add {{ENTITY_SINGULAR}}</h2>
      </div>
      <form id="create-form" class="form-grid" autocomplete="off"></form>
    </section>

    <section class="panel">
      <div class="panel-head">
        <h2>{{ENTITY_PLURAL_TITLE}}</h2>
        <input id="search" class="input" type="search" placeholder="Filter…" />
      </div>
      <div class="table-wrap">
        <table>
          <thead><tr id="table-head"></tr></thead>
          <tbody id="table-body"></tbody>
        </table>
        <p id="empty" class="empty" hidden>No records yet.</p>
      </div>
    </section>
  </div>

  <script src="{{STATIC_PREFIX}}/static/dashboard.js"></script>
</body>
</html>
"""


DASHBOARD_JS = """// {{TITLE}} dashboard logic. Generated by BuffStack.
(function () {
  "use strict";

  var API_ENDPOINT = "{{API_ENDPOINT}}";
  var REFRESH_MS = {{REFRESH_MS}};
  var COLUMNS = {{COLUMNS_JSON}};
  var FIELDS = {{FIELDS_JSON}};

  var state = { rows: [] };

  function el(id) { return document.getElementById(id); }

  function setStatus(text, kind) {
    var pill = el("status-pill");
    pill.textContent = text;
    pill.className = "pill pill-" + kind;
  }

  function showError(message) {
    var box = el("error");
    box.textContent = message;
    box.hidden = !message;
  }

  function buildForm() {
    var form = el("create-form");
    form.innerHTML = "";
    FIELDS.forEach(function (field) {
      var wrap = document.createElement("label");
      wrap.className = "field";
      var span = document.createElement("span");
      span.textContent = field.label;
      var input = document.createElement("input");
      input.className = "input";
      input.name = field.name;
      input.type = field.type === "integer" || field.type === "float" ? "number" : "text";
      input.required = !!field.required;
      wrap.appendChild(span);
      wrap.appendChild(input);
      form.appendChild(wrap);
    });
    var submit = document.createElement("button");
    submit.type = "submit";
    submit.className = "btn btn-primary";
    submit.textContent = "Create";
    form.appendChild(submit);
  }

  function buildHead() {
    var head = el("table-head");
    head.innerHTML = "";
    COLUMNS.forEach(function (column) {
      var th = document.createElement("th");
      th.textContent = column.label;
      head.appendChild(th);
    });
    var actions = document.createElement("th");
    actions.textContent = "";
    head.appendChild(actions);
  }

  function visibleRows() {
    var query = (el("search").value || "").toLowerCase();
    if (!query) return state.rows;
    return state.rows.filter(function (row) {
      return COLUMNS.some(function (column) {
        return String(row[column.key] == null ? "" : row[column.key])
          .toLowerCase()
          .indexOf(query) !== -1;
      });
    });
  }

  function render() {
    var body = el("table-body");
    body.innerHTML = "";
    var rows = visibleRows();
    el("empty").hidden = rows.length > 0;

    rows.forEach(function (row) {
      var tr = document.createElement("tr");
      COLUMNS.forEach(function (column) {
        var td = document.createElement("td");
        var value = row[column.key];
        td.textContent = value == null ? "" : String(value);
        tr.appendChild(td);
      });
      var tdActions = document.createElement("td");
      var del = document.createElement("button");
      del.className = "btn btn-danger";
      del.type = "button";
      del.textContent = "Delete";
      del.addEventListener("click", function () { remove(row.id); });
      tdActions.appendChild(del);
      tr.appendChild(tdActions);
      body.appendChild(tr);
    });
  }

  function load() {
    setStatus("loading…", "unknown");
    fetch(API_ENDPOINT, { headers: { Accept: "application/json" } })
      .then(function (response) {
        if (!response.ok) throw new Error("API returned " + response.status);
        return response.json();
      })
      .then(function (data) {
        // The store is authoritative; never keep a client-supplied id that
        // collides with a different record.
        state.rows = Array.isArray(data.items) ? data.items : [];
        showError("");
        setStatus("connected", "ok");
        el("kpi-count").textContent = String(data.count != null ? data.count : state.rows.length);
        el("kpi-updated").textContent = new Date().toLocaleTimeString();
        render();
      })
      .catch(function (error) {
        setStatus("offline", "error");
        showError("Could not reach " + API_ENDPOINT + ": " + error.message);
      });
  }

  function create(payload) {
    fetch(API_ENDPOINT, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    })
      .then(function (response) {
        if (!response.ok) throw new Error("API returned " + response.status);
        return response.json();
      })
      .then(load)
      .catch(function (error) { showError("Create failed: " + error.message); });
  }

  function remove(id) {
    fetch(API_ENDPOINT + "/" + id, { method: "DELETE" })
      .then(function (response) {
        if (!response.ok && response.status !== 404) {
          throw new Error("API returned " + response.status);
        }
        return load();
      })
      .catch(function (error) { showError("Delete failed: " + error.message); });
  }

  document.addEventListener("DOMContentLoaded", function () {
    buildHead();
    buildForm();
    el("refresh").addEventListener("click", load);
    el("search").addEventListener("input", render);
    el("create-form").addEventListener("submit", function (event) {
      event.preventDefault();
      var payload = {};
      FIELDS.forEach(function (field) {
        var input = event.target.elements[field.name];
        var raw = input ? input.value : "";
        if (raw === "") return;
        if (field.type === "integer") {
          var asInt = parseInt(raw, 10);
          payload[field.name] = Number.isNaN(asInt) ? raw : asInt;
        } else if (field.type === "float") {
          var asFloat = parseFloat(raw);
          payload[field.name] = Number.isNaN(asFloat) ? raw : asFloat;
        } else {
          payload[field.name] = raw;
        }
      });
      create(payload);
      event.target.reset();
    });
    load();
    if (REFRESH_MS > 0) setInterval(load, REFRESH_MS);
  });
})();
"""


DASHBOARD_CSS = """/* {{TITLE}} styling. Generated by BuffStack. */
:root {
  --bg: #0f1117;
  --panel: #171a23;
  --panel-2: #1e2230;
  --border: #2a2f3e;
  --text: #e6e9f0;
  --muted: #8b93a7;
  --accent: #6d8cff;
  --ok: #34d399;
  --error: #f87171;
}
* { box-sizing: border-box; }
body {
  margin: 0;
  background: var(--bg);
  color: var(--text);
  font: 15px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
}
.shell { max-width: 1080px; margin: 0 auto; padding: 32px 20px 64px; }
.topbar { display: flex; justify-content: space-between; align-items: flex-start; gap: 16px; }
.topbar h1 { margin: 0; font-size: 26px; letter-spacing: -0.02em; }
.subtitle { margin: 4px 0 0; color: var(--muted); }
.topbar-actions { display: flex; align-items: center; gap: 10px; }
.pill { padding: 5px 12px; border-radius: 999px; font-size: 12px; font-weight: 600; }
.pill-ok { background: rgba(52, 211, 153, 0.15); color: var(--ok); }
.pill-error { background: rgba(248, 113, 113, 0.15); color: var(--error); }
.pill-unknown { background: rgba(139, 147, 167, 0.15); color: var(--muted); }
.btn {
  background: var(--panel-2); color: var(--text); border: 1px solid var(--border);
  padding: 8px 14px; border-radius: 8px; cursor: pointer; font-size: 14px;
}
.btn:hover { border-color: var(--accent); }
.btn-primary { background: var(--accent); border-color: var(--accent); color: #0b0d13; font-weight: 600; }
.btn-danger { color: var(--error); }
.error {
  margin-top: 16px; padding: 12px 14px; border-radius: 8px;
  background: rgba(248, 113, 113, 0.12); color: var(--error);
  border: 1px solid rgba(248, 113, 113, 0.3);
}
.cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 14px; margin-top: 24px; }
.card { background: var(--panel); border: 1px solid var(--border); border-radius: 12px; padding: 16px; }
.card-label { display: block; color: var(--muted); font-size: 12px; text-transform: uppercase; letter-spacing: 0.06em; }
.card-value { display: block; margin-top: 8px; font-size: 28px; }
.card-value-sm { font-size: 15px; word-break: break-all; }
.panel { margin-top: 24px; background: var(--panel); border: 1px solid var(--border); border-radius: 12px; padding: 18px; }
.panel-head { display: flex; justify-content: space-between; align-items: center; gap: 12px; margin-bottom: 14px; }
.panel-head h2 { margin: 0; font-size: 16px; }
.form-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 12px; align-items: end; }
.field { display: flex; flex-direction: column; gap: 6px; }
.field span { color: var(--muted); font-size: 12px; }
.input {
  background: var(--panel-2); border: 1px solid var(--border); color: var(--text);
  padding: 9px 11px; border-radius: 8px; font-size: 14px; width: 100%;
}
.input:focus { outline: none; border-color: var(--accent); }
.table-wrap { overflow-x: auto; }
table { width: 100%; border-collapse: collapse; }
th, td { text-align: left; padding: 10px 12px; border-bottom: 1px solid var(--border); font-size: 14px; }
th { color: var(--muted); font-weight: 600; font-size: 12px; text-transform: uppercase; letter-spacing: 0.05em; }
tbody tr:hover { background: var(--panel-2); }
.empty { color: var(--muted); padding: 18px 0; margin: 0; }
"""


TEST_API_PY = '''"""Smoke tests for the {{PROJECT_NAME}} JSON API."""

from __future__ import annotations

import app as app_module


def client():
    application = app_module.create_app()
    application.config.update(TESTING=True)
    return application.test_client()


def test_health():
    response = client().get("/health")
    assert response.status_code == 200
    assert response.get_json() == {"status": "ok"}


def test_dashboard_is_served():
    response = client().get("/")
    assert response.status_code == 200
    body = response.get_data(as_text=True)
    assert "<html" in body.lower()
    assert "dashboard.js" in body


def test_list_returns_object():
    payload = client().get("/api/{{ENTITY_PLURAL}}").get_json()
    assert isinstance(payload, dict)
    assert "items" in payload


def test_create_and_delete_roundtrip():
    test_client = client()
    created = test_client.post("/api/{{ENTITY_PLURAL}}", json={{SAMPLE_PAYLOAD_JSON}})
    assert created.status_code == 201
    record = created.get_json()
    assert "id" in record

    listed = test_client.get("/api/{{ENTITY_PLURAL}}").get_json()
    assert any(item["id"] == record["id"] for item in listed["items"])

    fetched = test_client.get("/api/{{ENTITY_PLURAL}}/" + str(record["id"]))
    assert fetched.status_code == 200
    assert fetched.get_json()["id"] == record["id"]

    deleted = test_client.delete("/api/{{ENTITY_PLURAL}}/" + str(record["id"]))
    assert deleted.status_code == 200
    assert test_client.get("/api/{{ENTITY_PLURAL}}/" + str(record["id"])).status_code == 404
'''


def dashboard_columns(fields: list[dict[str, Any]]) -> list[dict[str, str]]:
    """Build dashboard columns from the entity field specs."""
    columns = [{"key": "id", "label": "ID"}]
    columns += [{"key": f["name"], "label": f["name"].replace("_", " ").title()} for f in fields]
    return columns


def dashboard_fields(fields: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Build the dashboard create-form fields from the entity field specs."""
    return [
        {
            "name": f["name"],
            "label": f["name"].replace("_", " ").title(),
            "type": f.get("type", "string"),
            "required": bool(f.get("required", False)),
        }
        for f in fields
    ]


def required_fields(fields: list[dict[str, Any]]) -> list[str]:
    """Names of the fields the create endpoint must receive."""
    return [f["name"] for f in fields if f.get("required")]


_SAMPLE_VALUES = {
    "string": "smoke",
    "integer": 1,
    "float": 1.0,
    "boolean": True,
    "datetime": "2024-01-01T00:00:00",
}


def sample_payload(fields: list[dict[str, Any]]) -> dict[str, Any]:
    """A valid create body for the generated smoke test."""
    return {f["name"]: _SAMPLE_VALUES.get(f.get("type", "string"), "smoke") for f in fields}


def json_literal(value: Any) -> str:
    return json.dumps(value)
